package com.poc.db.model;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aid
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private String aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.apassword
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private String apassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aname
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private String aname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aid
     *
     * @return the value of admin.aid
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aid
     *
     * @param aid the value for admin.aid
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setAid(String aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.apassword
     *
     * @return the value of admin.apassword
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public String getApassword() {
        return apassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.apassword
     *
     * @param apassword the value for admin.apassword
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setApassword(String apassword) {
        this.apassword = apassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aname
     *
     * @return the value of admin.aname
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aname
     *
     * @param aname the value for admin.aname
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setAname(String aname) {
        this.aname = aname;
    }
}