package com.poc.db.model;

public class Assessor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessor.asorid
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    private String asorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessor.id
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessor.aspassword
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    private String aspassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessor.asname
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    private String asname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessor.sex
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessor.mobile
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    private String mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessor.asorid
     *
     * @return the value of assessor.asorid
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    public String getAsorid() {
        return asorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessor.asorid
     *
     * @param asorid the value for assessor.asorid
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    public void setAsorid(String asorid) {
        this.asorid = asorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessor.id
     *
     * @return the value of assessor.id
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessor.id
     *
     * @param id the value for assessor.id
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessor.aspassword
     *
     * @return the value of assessor.aspassword
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    public String getAspassword() {
        return aspassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessor.aspassword
     *
     * @param aspassword the value for assessor.aspassword
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    public void setAspassword(String aspassword) {
        this.aspassword = aspassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessor.asname
     *
     * @return the value of assessor.asname
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    public String getAsname() {
        return asname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessor.asname
     *
     * @param asname the value for assessor.asname
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    public void setAsname(String asname) {
        this.asname = asname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessor.sex
     *
     * @return the value of assessor.sex
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessor.sex
     *
     * @param sex the value for assessor.sex
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessor.mobile
     *
     * @return the value of assessor.mobile
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessor.mobile
     *
     * @param mobile the value for assessor.mobile
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
}