package com.poc.db.model;

public class Assess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.asid
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    private String asid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.id
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.caseid
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    private int caseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.plateNumber
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    private String plateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.sum
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    private String sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.photo
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.apply_User
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    private String applyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.apply_User_Phone
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    private String applyUserPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.assessor
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    private String assessor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.assess_Time
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    private String assessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.descibe
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.asid
     *
     * @return the value of assess.asid
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public String getAsid() {
        return asid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.asid
     *
     * @param asid the value for assess.asid
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public void setAsid(String asid) {
        this.asid = asid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.id
     *
     * @return the value of assess.id
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.id
     *
     * @param id the value for assess.id
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.caseid
     *
     * @return the value of assess.caseid
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public int getCaseid() {
        return caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.caseid
     *
     * @param caseid the value for assess.caseid
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public void setCaseid(int caseid) {
        this.caseid = caseid;
    }

  

    public String getPlateNumber() {
		return plateNumber;
	}

	public void setPlateNumber(String plateNumber) {
		this.plateNumber = plateNumber;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.sum
     *
     * @return the value of assess.sum
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public String getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.sum
     *
     * @param sum the value for assess.sum
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public void setSum(String sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.photo
     *
     * @return the value of assess.photo
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.photo
     *
     * @param photo the value for assess.photo
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.apply_User
     *
     * @return the value of assess.apply_User
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public String getApplyUser() {
        return applyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.apply_User
     *
     * @param applyUser the value for assess.apply_User
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public void setApplyUser(String applyUser) {
        this.applyUser = applyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.apply_User_Phone
     *
     * @return the value of assess.apply_User_Phone
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public String getApplyUserPhone() {
        return applyUserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.apply_User_Phone
     *
     * @param applyUserPhone the value for assess.apply_User_Phone
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public void setApplyUserPhone(String applyUserPhone) {
        this.applyUserPhone = applyUserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.assessor
     *
     * @return the value of assess.assessor
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public String getAssessor() {
        return assessor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.assessor
     *
     * @param assessor the value for assess.assessor
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public void setAssessor(String assessor) {
        this.assessor = assessor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.assess_Time
     *
     * @return the value of assess.assess_Time
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public String getAssessTime() {
        return assessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.assess_Time
     *
     * @param assessTime the value for assess.assess_Time
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    public void setAssessTime(String assessTime) {
        this.assessTime = assessTime;
    }

	public String getDescribe() {
		return describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.descibe
     *
     * @return the value of assess.descibe
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    
}