package com.poc.db.model;

public class Auditor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditor.auid
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private String auid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditor.id
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditor.aupassword
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private String aupassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditor.mobile
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private String mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditor.auid
     *
     * @return the value of auditor.auid
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public String getAuid() {
        return auid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditor.auid
     *
     * @param auid the value for auditor.auid
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setAuid(String auid) {
        this.auid = auid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditor.id
     *
     * @return the value of auditor.id
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditor.id
     *
     * @param id the value for auditor.id
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditor.aupassword
     *
     * @return the value of auditor.aupassword
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public String getAupassword() {
        return aupassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditor.aupassword
     *
     * @param aupassword the value for auditor.aupassword
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setAupassword(String aupassword) {
        this.aupassword = aupassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditor.mobile
     *
     * @return the value of auditor.mobile
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditor.mobile
     *
     * @param mobile the value for auditor.mobile
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
}