package com.poc.db.model;

public class Claim {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.caseid
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String caseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.id
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.a1id
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String a1id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.a2id
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String a2id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.recognizee
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String recognizee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.plate_Number
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String plateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.case_TIme
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String caseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.case_Place
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String casePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.report_Time
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String reportTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.report_Person
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String reportPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.report_Person_Mobile
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String reportPersonMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.driver
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String driver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.driver_Mobile
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String driverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.claim_Time
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String claimTime;

    /**
     * status=0 未进行任何操作的理赔单
     * status=1 待定状态的理赔单
     * status=2 审核拒绝的理赔单
     * status=3 审核通过的理赔单
     * status=4 归档的理赔单
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.apply_User
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String applyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column claim.case_Describe
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    private String caseDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.caseid
     *
     * @return the value of claim.caseid
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getCaseid() {
        return caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.caseid
     *
     * @param caseid the value for claim.caseid
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setCaseid(String caseid) {
        this.caseid = caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.id
     *
     * @return the value of claim.id
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.id
     *
     * @param id the value for claim.id
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.a1id
     *
     * @return the value of claim.a1id
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getA1id() {
        return a1id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.a1id
     *
     * @param a1id the value for claim.a1id
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setA1id(String a1id) {
        this.a1id = a1id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.a2id
     *
     * @return the value of claim.a2id
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getA2id() {
        return a2id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.a2id
     *
     * @param a2id the value for claim.a2id
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setA2id(String a2id) {
        this.a2id = a2id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.recognizee
     *
     * @return the value of claim.recognizee
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getRecognizee() {
        return recognizee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.recognizee
     *
     * @param recognizee the value for claim.recognizee
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setRecognizee(String recognizee) {
        this.recognizee = recognizee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.plate_Number
     *
     * @return the value of claim.plate_Number
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.plate_Number
     *
     * @param plateNumber the value for claim.plate_Number
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.case_TIme
     *
     * @return the value of claim.case_TIme
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getCaseTime() {
        return caseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.case_TIme
     *
     * @param caseTime the value for claim.case_TIme
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setCaseTime(String caseTime) {
        this.caseTime = caseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.case_Place
     *
     * @return the value of claim.case_Place
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getCasePlace() {
        return casePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.case_Place
     *
     * @param casePlace the value for claim.case_Place
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setCasePlace(String casePlace) {
        this.casePlace = casePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.report_Time
     *
     * @return the value of claim.report_Time
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.report_Time
     *
     * @param reportTime the value for claim.report_Time
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setReportTime(String reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.report_Person
     *
     * @return the value of claim.report_Person
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getReportPerson() {
        return reportPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.report_Person
     *
     * @param reportPerson the value for claim.report_Person
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setReportPerson(String reportPerson) {
        this.reportPerson = reportPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.report_Person_Mobile
     *
     * @return the value of claim.report_Person_Mobile
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getReportPersonMobile() {
        return reportPersonMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.report_Person_Mobile
     *
     * @param reportPersonMobile the value for claim.report_Person_Mobile
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setReportPersonMobile(String reportPersonMobile) {
        this.reportPersonMobile = reportPersonMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.driver
     *
     * @return the value of claim.driver
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getDriver() {
        return driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.driver
     *
     * @param driver the value for claim.driver
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setDriver(String driver) {
        this.driver = driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.driver_Mobile
     *
     * @return the value of claim.driver_Mobile
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getDriverMobile() {
        return driverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.driver_Mobile
     *
     * @param driverMobile the value for claim.driver_Mobile
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setDriverMobile(String driverMobile) {
        this.driverMobile = driverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.claim_Time
     *
     * @return the value of claim.claim_Time
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getClaimTime() {
        return claimTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.claim_Time
     *
     * @param claimTime the value for claim.claim_Time
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setClaimTime(String claimTime) {
        this.claimTime = claimTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.status
     *
     * @return the value of claim.status
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.status
     *
     * @param status the value for claim.status
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.apply_User
     *
     * @return the value of claim.apply_User
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getApplyUser() {
        return applyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.apply_User
     *
     * @param applyUser the value for claim.apply_User
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setApplyUser(String applyUser) {
        this.applyUser = applyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column claim.case_Describe
     *
     * @return the value of claim.case_Describe
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public String getCaseDescribe() {
        return caseDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column claim.case_Describe
     *
     * @param caseDescribe the value for claim.case_Describe
     *
     * @mbggenerated Wed Mar 08 14:38:21 CST 2017
     */
    public void setCaseDescribe(String caseDescribe) {
        this.caseDescribe = caseDescribe;
    }
}