package com.poc.db.model;

public class Policy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy.policyid
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private String policyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy.id
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy.policy_Type
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private String policyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy.recognizee
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private String recognizee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy.plate_Number
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private String plateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy.sum
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private Integer sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy.startTime
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy.endTime
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    private String endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy.policyid
     *
     * @return the value of policy.policyid
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public String getPolicyid() {
        return policyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy.policyid
     *
     * @param policyid the value for policy.policyid
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setPolicyid(String policyid) {
        this.policyid = policyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy.id
     *
     * @return the value of policy.id
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy.id
     *
     * @param id the value for policy.id
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy.policy_Type
     *
     * @return the value of policy.policy_Type
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public String getPolicyType() {
        return policyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy.policy_Type
     *
     * @param policyType the value for policy.policy_Type
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setPolicyType(String policyType) {
        this.policyType = policyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy.recognizee
     *
     * @return the value of policy.recognizee
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public String getRecognizee() {
        return recognizee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy.recognizee
     *
     * @param recognizee the value for policy.recognizee
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setRecognizee(String recognizee) {
        this.recognizee = recognizee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy.plate_Number
     *
     * @return the value of policy.plate_Number
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy.plate_Number
     *
     * @param plateNumber the value for policy.plate_Number
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy.sum
     *
     * @return the value of policy.sum
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy.sum
     *
     * @param sum the value for policy.sum
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy.startTime
     *
     * @return the value of policy.startTime
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy.startTime
     *
     * @param starttime the value for policy.startTime
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy.endTime
     *
     * @return the value of policy.endTime
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy.endTime
     *
     * @param endtime the value for policy.endTime
     *
     * @mbggenerated Tue Mar 07 14:06:20 CST 2017
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }
}