package com.poc.db.dao;

import org.apache.ibatis.annotations.Param;

import com.poc.db.model.Assessor;

public interface AssessorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessor
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    int deleteByPrimaryKey(String asorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessor
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    int insert(Assessor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessor
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    int insertSelective(Assessor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessor
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    Assessor selectByPrimaryKey(String asorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessor
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    int updateByPrimaryKeySelective(Assessor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessor
     *
     * @mbggenerated Wed Mar 08 13:47:17 CST 2017
     */
    int updateByPrimaryKey(Assessor record);
    
    Assessor assessorLogin(@Param("asorid")String asorid,@Param("aspassword")String aspassword);
}