package com.poc.db.dao;

import java.util.List;

import com.poc.db.model.Assess;

public interface AssessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    int deleteByPrimaryKey(String asid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    int insert(Assess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    int insertSelective(Assess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    Assess selectByPrimaryKey(String asid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    int updateByPrimaryKeySelective(Assess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Assess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbggenerated Wed Mar 08 10:29:49 CST 2017
     */
    int updateByPrimaryKey(Assess record);
    
    
    List<Assess> showAssess(Assess record);
}