package com.poc.db.dao;

import org.apache.ibatis.annotations.Param;

import com.poc.db.model.Auditor;

public interface AuditorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated Fri Feb 24 01:58:56 CST 2017
     */
    int insert(Auditor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditor
     *
     * @mbggenerated Fri Feb 24 01:58:56 CST 2017
     */
    int insertSelective(Auditor record);
    
    Auditor auditorLogin(@Param("auid")String auid,@Param("aupassword")String aupassword);
}