package com.poc.db.dao;

import java.util.List;

import com.poc.db.model.Policy;

public interface PolicyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated Fri Feb 24 01:58:56 CST 2017
     */
    int deleteByPrimaryKey(String poid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated Fri Feb 24 01:58:56 CST 2017
     */
    int insert(Policy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated Fri Feb 24 01:58:56 CST 2017
     */
    int insertSelective(Policy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated Fri Feb 24 01:58:56 CST 2017
     */
    Policy selectByPrimaryKey(String poid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated Fri Feb 24 01:58:56 CST 2017
     */
    int updateByPrimaryKeySelective(Policy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated Fri Feb 24 01:58:56 CST 2017
     */
    int updateByPrimaryKey(Policy record);
    
    List<Policy> showAllPolicyByUserId(String uid);
}